framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Message\Ping': async

bref_messenger:
    sqs: true # Register the SQS transport

services:

    my_sqs_consumer:
        class: Bref\Symfony\Messenger\Service\Sqs\SqsConsumer
        arguments:
            - '@Bref\Symfony\Messenger\Service\BusDriver'
            - '@messenger.routable_message_bus'
            - '@Symfony\Component\Messenger\Transport\Serialization\SerializerInterface'
            - 'async' # Same as transport name
        tags:
            - { name: bref_messenger.consumer }